//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.UnitTest.MyWebWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/SOA.Web.Remoting")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWebWCF.IMyWCF")]
    public interface IMyWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/DoWork", ReplyAction="http://tempuri.org/IMyWCF/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/DoWork", ReplyAction="http://tempuri.org/IMyWCF/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/GetString", ReplyAction="http://tempuri.org/IMyWCF/GetStringResponse")]
        string GetString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/GetString", ReplyAction="http://tempuri.org/IMyWCF/GetStringResponse")]
        System.Threading.Tasks.Task<string> GetStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/GetUsers", ReplyAction="http://tempuri.org/IMyWCF/GetUsersResponse")]
        SOA.UnitTest.MyWebWCF.User[] GetUsers(int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/GetUsers", ReplyAction="http://tempuri.org/IMyWCF/GetUsersResponse")]
        System.Threading.Tasks.Task<SOA.UnitTest.MyWebWCF.User[]> GetUsersAsync(int index);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyWCFChannel : SOA.UnitTest.MyWebWCF.IMyWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWCFClient : System.ServiceModel.ClientBase<SOA.UnitTest.MyWebWCF.IMyWCF>, SOA.UnitTest.MyWebWCF.IMyWCF {
        
        public MyWCFClient() {
        }
        
        public MyWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string GetString() {
            return base.Channel.GetString();
        }
        
        public System.Threading.Tasks.Task<string> GetStringAsync() {
            return base.Channel.GetStringAsync();
        }
        
        public SOA.UnitTest.MyWebWCF.User[] GetUsers(int index) {
            return base.Channel.GetUsers(index);
        }
        
        public System.Threading.Tasks.Task<SOA.UnitTest.MyWebWCF.User[]> GetUsersAsync(int index) {
            return base.Channel.GetUsersAsync(index);
        }
    }
}
